AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10